package me.himi.love.im.util;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import me.himi.love.im.entity.FaceText;
import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.text.Spannable;
import android.text.SpannableString;
import android.text.TextUtils;
import android.text.style.ImageSpan;

public class FaceTextUtils {

    public static List<FaceText> faceTexts = new ArrayList<FaceText>();
    static {
	faceTexts.add(new FaceText("\\ue056"));
	faceTexts.add(new FaceText("\\ue057"));
	faceTexts.add(new FaceText("\\ue058"));
	faceTexts.add(new FaceText("\\ue059"));
	faceTexts.add(new FaceText("\\ue105"));
	faceTexts.add(new FaceText("\\ue106"));
	faceTexts.add(new FaceText("\\ue107"));
	faceTexts.add(new FaceText("\\ue108"));
	faceTexts.add(new FaceText("\\ue401"));
	faceTexts.add(new FaceText("\\ue402"));
	faceTexts.add(new FaceText("\\ue403"));
	faceTexts.add(new FaceText("\\ue404"));
	faceTexts.add(new FaceText("\\ue405"));
	faceTexts.add(new FaceText("\\ue406"));
	faceTexts.add(new FaceText("\\ue407"));
	faceTexts.add(new FaceText("\\ue408"));
	faceTexts.add(new FaceText("\\ue409"));
	faceTexts.add(new FaceText("\\ue40a"));
	faceTexts.add(new FaceText("\\ue40b"));
	faceTexts.add(new FaceText("\\ue40d"));
	faceTexts.add(new FaceText("\\ue40e"));
	faceTexts.add(new FaceText("\\ue40f"));
	faceTexts.add(new FaceText("\\ue410"));
	faceTexts.add(new FaceText("\\ue411"));
	faceTexts.add(new FaceText("\\ue412"));
	faceTexts.add(new FaceText("\\ue413"));
	faceTexts.add(new FaceText("\\ue414"));
	faceTexts.add(new FaceText("\\ue415"));
	faceTexts.add(new FaceText("\\ue416"));
	faceTexts.add(new FaceText("\\ue417"));
	faceTexts.add(new FaceText("\\ue418"));
	faceTexts.add(new FaceText("\\ue41f"));
	faceTexts.add(new FaceText("\\ue00e"));
	faceTexts.add(new FaceText("\\ue421"));

    }

//    public static List<FaceText> faceTexts2 = new ArrayList<FaceText>();
//    static {
//	faceTexts2.add(new FaceText("\\ue1352"));
//	faceTexts2.add(new FaceText("\\ue1353"));
//	faceTexts2.add(new FaceText("\\ue1354"));
//	faceTexts2.add(new FaceText("\\ue1355"));
//	faceTexts2.add(new FaceText("\\ue1356"));
//	faceTexts2.add(new FaceText("\\ue1357"));
//	faceTexts2.add(new FaceText("\\ue1358"));
//	faceTexts2.add(new FaceText("\\ue1359"));
//	faceTexts2.add(new FaceText("\\ue1360"));
//	faceTexts2.add(new FaceText("\\ue1361"));
//	faceTexts2.add(new FaceText("\\ue1362"));
//	faceTexts2.add(new FaceText("\\ue1363"));
//	faceTexts2.add(new FaceText("\\ue1364"));
//	faceTexts2.add(new FaceText("\\ue1365"));
//	faceTexts2.add(new FaceText("\\ue1366"));
//	faceTexts2.add(new FaceText("\\ue1367"));
//	faceTexts2.add(new FaceText("\\ue1368"));
//	faceTexts2.add(new FaceText("\\ue1369"));
//	faceTexts2.add(new FaceText("\\ue1370"));
//	faceTexts2.add(new FaceText("\\ue1371"));
//	faceTexts2.add(new FaceText("\\ue1372"));
//	faceTexts2.add(new FaceText("\\ue1373"));
//	faceTexts2.add(new FaceText("\\ue1374"));
//	faceTexts2.add(new FaceText("\\ue1375"));
//	faceTexts2.add(new FaceText("\\ue1376"));
//	faceTexts2.add(new FaceText("\\ue1377"));
//	faceTexts2.add(new FaceText("\\ue1378"));
//	faceTexts2.add(new FaceText("\\ue1379"));
//	faceTexts2.add(new FaceText("\\ue1380"));
//	faceTexts2.add(new FaceText("\\ue1381"));
//	faceTexts2.add(new FaceText("\\ue1382"));
//	faceTexts2.add(new FaceText("\\ue1383"));
//	faceTexts2.add(new FaceText("\\ue1384"));
//	faceTexts2.add(new FaceText("\\ue1385"));
//	faceTexts2.add(new FaceText("\\ue1386"));
//	faceTexts2.add(new FaceText("\\ue1387"));
//	faceTexts2.add(new FaceText("\\ue1388"));
//	faceTexts2.add(new FaceText("\\ue1389"));
//	faceTexts2.add(new FaceText("\\ue1390"));
//	faceTexts2.add(new FaceText("\\ue1391"));
//	faceTexts2.add(new FaceText("\\ue1392"));
//	faceTexts2.add(new FaceText("\\ue1393"));
//	faceTexts2.add(new FaceText("\\ue1394"));
//	faceTexts2.add(new FaceText("\\ue1395"));
//	faceTexts2.add(new FaceText("\\ue1396"));
//	faceTexts2.add(new FaceText("\\ue1397"));
//	faceTexts2.add(new FaceText("\\ue1398"));
//	faceTexts2.add(new FaceText("\\ue1399"));
//	faceTexts2.add(new FaceText("\\ue1400"));
//	faceTexts2.add(new FaceText("\\ue1401"));
//	faceTexts2.add(new FaceText("\\ue1402"));
//	faceTexts2.add(new FaceText("\\ue1403"));
//	faceTexts2.add(new FaceText("\\ue1404"));
//	faceTexts2.add(new FaceText("\\ue1405"));
//	faceTexts2.add(new FaceText("\\ue1406"));
//	faceTexts2.add(new FaceText("\\ue1407"));
//	faceTexts2.add(new FaceText("\\ue1408"));
//	faceTexts2.add(new FaceText("\\ue1409"));
//	faceTexts2.add(new FaceText("\\ue1410"));
//	faceTexts2.add(new FaceText("\\ue1411"));
//	faceTexts2.add(new FaceText("\\ue1412"));
//	faceTexts2.add(new FaceText("\\ue1413"));
//	faceTexts2.add(new FaceText("\\ue1414"));
//	faceTexts2.add(new FaceText("\\ue1415"));
//	faceTexts2.add(new FaceText("\\ue1416"));
//	faceTexts2.add(new FaceText("\\ue1417"));
//	faceTexts2.add(new FaceText("\\ue1418"));
//	faceTexts2.add(new FaceText("\\ue1419"));
//	faceTexts2.add(new FaceText("\\ue1420"));
//	faceTexts2.add(new FaceText("\\ue1421"));
//	faceTexts2.add(new FaceText("\\ue1422"));
//
//
//	
//	faceTexts2.add(new FaceText("\\ue590"));
//	faceTexts2.add(new FaceText("\\ue591"));
//	faceTexts2.add(new FaceText("\\ue592"));
//	faceTexts2.add(new FaceText("\\ue593"));
//	faceTexts2.add(new FaceText("\\ue594"));
//	faceTexts2.add(new FaceText("\\ue595"));
//	faceTexts2.add(new FaceText("\\ue596"));
//	faceTexts2.add(new FaceText("\\ue597"));
//	faceTexts2.add(new FaceText("\\ue598"));
//	faceTexts2.add(new FaceText("\\ue599"));
//	faceTexts2.add(new FaceText("\\ue600"));
//	faceTexts2.add(new FaceText("\\ue601"));
//	faceTexts2.add(new FaceText("\\ue602"));
//	faceTexts2.add(new FaceText("\\ue603"));
//	faceTexts2.add(new FaceText("\\ue604"));
//	faceTexts2.add(new FaceText("\\ue605"));
//	faceTexts2.add(new FaceText("\\ue606"));
//	faceTexts2.add(new FaceText("\\ue607"));
//	faceTexts2.add(new FaceText("\\ue608"));
//	faceTexts2.add(new FaceText("\\ue609"));
//	faceTexts2.add(new FaceText("\\ue610"));
//	faceTexts2.add(new FaceText("\\ue611"));
//	faceTexts2.add(new FaceText("\\ue612"));
//	faceTexts2.add(new FaceText("\\ue613"));
//	faceTexts2.add(new FaceText("\\ue614"));
//	faceTexts2.add(new FaceText("\\ue615"));
//	faceTexts2.add(new FaceText("\\ue616"));
//	faceTexts2.add(new FaceText("\\ue617"));
//	faceTexts2.add(new FaceText("\\ue618"));
//	faceTexts2.add(new FaceText("\\ue619"));
//	faceTexts2.add(new FaceText("\\ue620"));
//	faceTexts2.add(new FaceText("\\ue621"));
//	faceTexts2.add(new FaceText("\\ue622"));
//	faceTexts2.add(new FaceText("\\ue623"));
//	faceTexts2.add(new FaceText("\\ue624"));
//	faceTexts2.add(new FaceText("\\ue625"));
//	faceTexts2.add(new FaceText("\\ue626"));
//	faceTexts2.add(new FaceText("\\ue627"));
//	faceTexts2.add(new FaceText("\\ue628"));
//	faceTexts2.add(new FaceText("\\ue629"));
//	faceTexts2.add(new FaceText("\\ue630"));
//	faceTexts2.add(new FaceText("\\ue631"));
//	faceTexts2.add(new FaceText("\\ue632"));
//	faceTexts2.add(new FaceText("\\ue633"));
//	faceTexts2.add(new FaceText("\\ue634"));
//	faceTexts2.add(new FaceText("\\ue635"));
//	faceTexts2.add(new FaceText("\\ue636"));
//	faceTexts2.add(new FaceText("\\ue637"));
//	faceTexts2.add(new FaceText("\\ue638"));
//	faceTexts2.add(new FaceText("\\ue639"));
//	faceTexts2.add(new FaceText("\\ue640"));
//	faceTexts2.add(new FaceText("\\ue641"));
//	faceTexts2.add(new FaceText("\\ue642"));
//	faceTexts2.add(new FaceText("\\ue643"));
//	faceTexts2.add(new FaceText("\\ue644"));
//	faceTexts2.add(new FaceText("\\ue645"));
//	faceTexts2.add(new FaceText("\\ue646"));
//	faceTexts2.add(new FaceText("\\ue647"));
//	faceTexts2.add(new FaceText("\\ue648"));
//	faceTexts2.add(new FaceText("\\ue649"));
//	faceTexts2.add(new FaceText("\\ue650"));
//	faceTexts2.add(new FaceText("\\ue651"));
//	faceTexts2.add(new FaceText("\\ue652"));
//	faceTexts2.add(new FaceText("\\ue653"));
//	faceTexts2.add(new FaceText("\\ue654"));
//	faceTexts2.add(new FaceText("\\ue655"));
//	faceTexts2.add(new FaceText("\\ue656"));
//	faceTexts2.add(new FaceText("\\ue657"));
//	faceTexts2.add(new FaceText("\\ue658"));
//	faceTexts2.add(new FaceText("\\ue659"));
//	faceTexts2.add(new FaceText("\\ue660"));
//	faceTexts2.add(new FaceText("\\ue661"));
//	faceTexts2.add(new FaceText("\\ue662"));
//	faceTexts2.add(new FaceText("\\ue663"));
//	faceTexts2.add(new FaceText("\\ue664"));
//	faceTexts2.add(new FaceText("\\ue665"));
//	faceTexts2.add(new FaceText("\\ue666"));
//	faceTexts2.add(new FaceText("\\ue667"));
//	faceTexts2.add(new FaceText("\\ue668"));
//	faceTexts2.add(new FaceText("\\ue669"));
//	faceTexts2.add(new FaceText("\\ue670"));
//	faceTexts2.add(new FaceText("\\ue671"));
//	faceTexts2.add(new FaceText("\\ue672"));
//	faceTexts2.add(new FaceText("\\ue673"));
//	faceTexts2.add(new FaceText("\\ue674"));
//	faceTexts2.add(new FaceText("\\ue675"));
//	faceTexts2.add(new FaceText("\\ue676"));
//	faceTexts2.add(new FaceText("\\ue677"));
//	faceTexts2.add(new FaceText("\\ue678"));
//	faceTexts2.add(new FaceText("\\ue679"));
//	faceTexts2.add(new FaceText("\\ue680"));
//	faceTexts2.add(new FaceText("\\ue681"));
//	faceTexts2.add(new FaceText("\\ue682"));
//	faceTexts2.add(new FaceText("\\ue683"));
//	faceTexts2.add(new FaceText("\\ue684"));
//	faceTexts2.add(new FaceText("\\ue685"));
//	faceTexts2.add(new FaceText("\\ue686"));
//	faceTexts2.add(new FaceText("\\ue687"));
//	faceTexts2.add(new FaceText("\\ue688"));
//	faceTexts2.add(new FaceText("\\ue689"));
//	faceTexts2.add(new FaceText("\\ue690"));
//	faceTexts2.add(new FaceText("\\ue691"));
//	faceTexts2.add(new FaceText("\\ue692"));
//	faceTexts2.add(new FaceText("\\ue693"));
//	faceTexts2.add(new FaceText("\\ue694"));
//	faceTexts2.add(new FaceText("\\ue695"));
//	faceTexts2.add(new FaceText("\\ue696"));
//	faceTexts2.add(new FaceText("\\ue697"));
//	faceTexts2.add(new FaceText("\\ue698"));
//	faceTexts2.add(new FaceText("\\ue699"));
//	faceTexts2.add(new FaceText("\\ue700"));
//	faceTexts2.add(new FaceText("\\ue701"));
//	faceTexts2.add(new FaceText("\\ue702"));
//	faceTexts2.add(new FaceText("\\ue703"));
//	faceTexts2.add(new FaceText("\\ue704"));
//	faceTexts2.add(new FaceText("\\ue705"));
//	faceTexts2.add(new FaceText("\\ue706"));
//	faceTexts2.add(new FaceText("\\ue707"));
//	faceTexts2.add(new FaceText("\\ue708"));
//	faceTexts2.add(new FaceText("\\ue709"));
//	faceTexts2.add(new FaceText("\\ue710"));
//	faceTexts2.add(new FaceText("\\ue711"));
//	faceTexts2.add(new FaceText("\\ue712"));
//	faceTexts2.add(new FaceText("\\ue713"));
//	faceTexts2.add(new FaceText("\\ue714"));
//	faceTexts2.add(new FaceText("\\ue715"));
//	faceTexts2.add(new FaceText("\\ue716"));
//	faceTexts2.add(new FaceText("\\ue717"));
//	faceTexts2.add(new FaceText("\\ue718"));
//	faceTexts2.add(new FaceText("\\ue719"));
//	faceTexts2.add(new FaceText("\\ue720"));
//	faceTexts2.add(new FaceText("\\ue721"));
//	faceTexts2.add(new FaceText("\\ue722"));
//	faceTexts2.add(new FaceText("\\ue723"));
//	faceTexts2.add(new FaceText("\\ue724"));
//	faceTexts2.add(new FaceText("\\ue725"));
//	faceTexts2.add(new FaceText("\\ue726"));
//	faceTexts2.add(new FaceText("\\ue727"));
//	faceTexts2.add(new FaceText("\\ue728"));
//	faceTexts2.add(new FaceText("\\ue729"));
//	faceTexts2.add(new FaceText("\\ue730"));
//	faceTexts2.add(new FaceText("\\ue731"));
//	faceTexts2.add(new FaceText("\\ue732"));
//	faceTexts2.add(new FaceText("\\ue733"));
//	faceTexts2.add(new FaceText("\\ue734"));
//	faceTexts2.add(new FaceText("\\ue735"));
//	faceTexts2.add(new FaceText("\\ue736"));
//	faceTexts2.add(new FaceText("\\ue737"));
//	faceTexts2.add(new FaceText("\\ue738"));
//	faceTexts2.add(new FaceText("\\ue739"));
//	faceTexts2.add(new FaceText("\\ue740"));
//	faceTexts2.add(new FaceText("\\ue741"));
//	faceTexts2.add(new FaceText("\\ue742"));
//	faceTexts2.add(new FaceText("\\ue743"));
//	faceTexts2.add(new FaceText("\\ue744"));
//	faceTexts2.add(new FaceText("\\ue745"));
//	faceTexts2.add(new FaceText("\\ue746"));
//	faceTexts2.add(new FaceText("\\ue747"));
//	faceTexts2.add(new FaceText("\\ue748"));
//	faceTexts2.add(new FaceText("\\ue749"));
//	faceTexts2.add(new FaceText("\\ue750"));
//	faceTexts2.add(new FaceText("\\ue751"));
//	faceTexts2.add(new FaceText("\\ue752"));
//	faceTexts2.add(new FaceText("\\ue753"));
//	faceTexts2.add(new FaceText("\\ue754"));
//	faceTexts2.add(new FaceText("\\ue755"));
//	faceTexts2.add(new FaceText("\\ue756"));
//	faceTexts2.add(new FaceText("\\ue757"));
//	faceTexts2.add(new FaceText("\\ue758"));
//	faceTexts2.add(new FaceText("\\ue759"));
//	faceTexts2.add(new FaceText("\\ue760"));
//	faceTexts2.add(new FaceText("\\ue761"));
//	faceTexts2.add(new FaceText("\\ue762"));
//	faceTexts2.add(new FaceText("\\ue763"));
//	faceTexts2.add(new FaceText("\\ue764"));
//	faceTexts2.add(new FaceText("\\ue765"));
//	faceTexts2.add(new FaceText("\\ue766"));
//	faceTexts2.add(new FaceText("\\ue767"));
//	faceTexts2.add(new FaceText("\\ue768"));
//	faceTexts2.add(new FaceText("\\ue769"));
//	faceTexts2.add(new FaceText("\\ue770"));
//	faceTexts2.add(new FaceText("\\ue771"));
//	faceTexts2.add(new FaceText("\\ue772"));
//	faceTexts2.add(new FaceText("\\ue773"));
//	faceTexts2.add(new FaceText("\\ue774"));
//	faceTexts2.add(new FaceText("\\ue775"));
//	faceTexts2.add(new FaceText("\\ue776"));
//	faceTexts2.add(new FaceText("\\ue777"));
//	faceTexts2.add(new FaceText("\\ue778"));
//	faceTexts2.add(new FaceText("\\ue779"));
//	faceTexts2.add(new FaceText("\\ue780"));
//	faceTexts2.add(new FaceText("\\ue781"));
//	faceTexts2.add(new FaceText("\\ue782"));
//	faceTexts2.add(new FaceText("\\ue783"));
//	faceTexts2.add(new FaceText("\\ue784"));
//	faceTexts2.add(new FaceText("\\ue785"));
//	faceTexts2.add(new FaceText("\\ue786"));
//	faceTexts2.add(new FaceText("\\ue787"));
//	faceTexts2.add(new FaceText("\\ue788"));
//	faceTexts2.add(new FaceText("\\ue789"));
//	faceTexts2.add(new FaceText("\\ue790"));
//	faceTexts2.add(new FaceText("\\ue791"));
//	faceTexts2.add(new FaceText("\\ue792"));
//	faceTexts2.add(new FaceText("\\ue793"));
//	faceTexts2.add(new FaceText("\\ue794"));
//	faceTexts2.add(new FaceText("\\ue795"));
//	faceTexts2.add(new FaceText("\\ue796"));
//	faceTexts2.add(new FaceText("\\ue797"));
//	faceTexts2.add(new FaceText("\\ue798"));
//	faceTexts2.add(new FaceText("\\ue799"));
//	faceTexts2.add(new FaceText("\\ue800"));
//	faceTexts2.add(new FaceText("\\ue801"));
//	faceTexts2.add(new FaceText("\\ue802"));
//	faceTexts2.add(new FaceText("\\ue803"));
//	faceTexts2.add(new FaceText("\\ue804"));
//	faceTexts2.add(new FaceText("\\ue805"));
//	faceTexts2.add(new FaceText("\\ue806"));
//	faceTexts2.add(new FaceText("\\ue807"));
//	faceTexts2.add(new FaceText("\\ue808"));
//	faceTexts2.add(new FaceText("\\ue809"));
//	faceTexts2.add(new FaceText("\\ue810"));
//	faceTexts2.add(new FaceText("\\ue811"));
//	faceTexts2.add(new FaceText("\\ue812"));
//	faceTexts2.add(new FaceText("\\ue813"));
//	faceTexts2.add(new FaceText("\\ue814"));
//	faceTexts2.add(new FaceText("\\ue815"));
//	faceTexts2.add(new FaceText("\\ue816"));
//	faceTexts2.add(new FaceText("\\ue817"));
//	faceTexts2.add(new FaceText("\\ue818"));
//	faceTexts2.add(new FaceText("\\ue819"));
//	faceTexts2.add(new FaceText("\\ue820"));
//	faceTexts2.add(new FaceText("\\ue821"));
//	faceTexts2.add(new FaceText("\\ue822"));
//	faceTexts2.add(new FaceText("\\ue823"));
//	faceTexts2.add(new FaceText("\\ue824"));
//	faceTexts2.add(new FaceText("\\ue825"));
//	faceTexts2.add(new FaceText("\\ue826"));
//	faceTexts2.add(new FaceText("\\ue827"));
//	faceTexts2.add(new FaceText("\\ue828"));
//	faceTexts2.add(new FaceText("\\ue829"));
//	faceTexts2.add(new FaceText("\\ue830"));
//	faceTexts2.add(new FaceText("\\ue831"));
//	faceTexts2.add(new FaceText("\\ue832"));
//	faceTexts2.add(new FaceText("\\ue833"));
//	faceTexts2.add(new FaceText("\\ue834"));
//	faceTexts2.add(new FaceText("\\ue835"));
//	faceTexts2.add(new FaceText("\\ue836"));
//	faceTexts2.add(new FaceText("\\ue837"));
//	faceTexts2.add(new FaceText("\\ue838"));
//	faceTexts2.add(new FaceText("\\ue839"));
//	faceTexts2.add(new FaceText("\\ue840"));
//	faceTexts2.add(new FaceText("\\ue841"));
//	faceTexts2.add(new FaceText("\\ue842"));
//	faceTexts2.add(new FaceText("\\ue843"));
//	faceTexts2.add(new FaceText("\\ue844"));
//	faceTexts2.add(new FaceText("\\ue845"));
//	faceTexts2.add(new FaceText("\\ue846"));
//	faceTexts2.add(new FaceText("\\ue847"));
//	faceTexts2.add(new FaceText("\\ue848"));
//	faceTexts2.add(new FaceText("\\ue849"));
//	faceTexts2.add(new FaceText("\\ue850"));
//	faceTexts2.add(new FaceText("\\ue851"));
//	faceTexts2.add(new FaceText("\\ue852"));
//	faceTexts2.add(new FaceText("\\ue853"));
//	faceTexts2.add(new FaceText("\\ue854"));
//	faceTexts2.add(new FaceText("\\ue855"));
//	faceTexts2.add(new FaceText("\\ue856"));
//	faceTexts2.add(new FaceText("\\ue857"));
//	faceTexts2.add(new FaceText("\\ue858"));
//	faceTexts2.add(new FaceText("\\ue859"));
//	faceTexts2.add(new FaceText("\\ue860"));
//	faceTexts2.add(new FaceText("\\ue861"));
//	faceTexts2.add(new FaceText("\\ue862"));
//	faceTexts2.add(new FaceText("\\ue863"));
//	faceTexts2.add(new FaceText("\\ue864"));
//	faceTexts2.add(new FaceText("\\ue865"));
//	faceTexts2.add(new FaceText("\\ue866"));
//	faceTexts2.add(new FaceText("\\ue867"));
//	faceTexts2.add(new FaceText("\\ue868"));
//	faceTexts2.add(new FaceText("\\ue869"));
//	faceTexts2.add(new FaceText("\\ue870"));
//	faceTexts2.add(new FaceText("\\ue871"));
//	faceTexts2.add(new FaceText("\\ue872"));
//	faceTexts2.add(new FaceText("\\ue873"));
//	faceTexts2.add(new FaceText("\\ue874"));
//	faceTexts2.add(new FaceText("\\ue875"));
//	faceTexts2.add(new FaceText("\\ue876"));
//	faceTexts2.add(new FaceText("\\ue877"));
//	faceTexts2.add(new FaceText("\\ue878"));
//	faceTexts2.add(new FaceText("\\ue879"));
//	faceTexts2.add(new FaceText("\\ue880"));
//	faceTexts2.add(new FaceText("\\ue881"));
//	faceTexts2.add(new FaceText("\\ue882"));
//	faceTexts2.add(new FaceText("\\ue883"));
//	faceTexts2.add(new FaceText("\\ue884"));
//	faceTexts2.add(new FaceText("\\ue885"));
//	faceTexts2.add(new FaceText("\\ue886"));
//	faceTexts2.add(new FaceText("\\ue887"));
//	faceTexts2.add(new FaceText("\\ue888"));
//	faceTexts2.add(new FaceText("\\ue889"));
//	faceTexts2.add(new FaceText("\\ue890"));
//	faceTexts2.add(new FaceText("\\ue891"));
//	faceTexts2.add(new FaceText("\\ue892"));
//	faceTexts2.add(new FaceText("\\ue893"));
//	faceTexts2.add(new FaceText("\\ue894"));
//	faceTexts2.add(new FaceText("\\ue895"));
//	faceTexts2.add(new FaceText("\\ue896"));
//	faceTexts2.add(new FaceText("\\ue897"));
//	faceTexts2.add(new FaceText("\\ue898"));
//	faceTexts2.add(new FaceText("\\ue899"));
//	faceTexts2.add(new FaceText("\\ue900"));
//	faceTexts2.add(new FaceText("\\ue901"));
//	faceTexts2.add(new FaceText("\\ue902"));
//	faceTexts2.add(new FaceText("\\ue903"));
//	faceTexts2.add(new FaceText("\\ue904"));
//	faceTexts2.add(new FaceText("\\ue905"));
//	faceTexts2.add(new FaceText("\\ue906"));
//	faceTexts2.add(new FaceText("\\ue907"));
//	faceTexts2.add(new FaceText("\\ue908"));
//	faceTexts2.add(new FaceText("\\ue909"));
//	faceTexts2.add(new FaceText("\\ue910"));
//	faceTexts2.add(new FaceText("\\ue911"));
//	faceTexts2.add(new FaceText("\\ue912"));
//	faceTexts2.add(new FaceText("\\ue913"));
//	faceTexts2.add(new FaceText("\\ue914"));
//	faceTexts2.add(new FaceText("\\ue915"));
//	faceTexts2.add(new FaceText("\\ue916"));
//	faceTexts2.add(new FaceText("\\ue917"));
//	faceTexts2.add(new FaceText("\\ue918"));
//	faceTexts2.add(new FaceText("\\ue919"));
//	faceTexts2.add(new FaceText("\\ue920"));
//	faceTexts2.add(new FaceText("\\ue921"));
//	faceTexts2.add(new FaceText("\\ue922"));
//	faceTexts2.add(new FaceText("\\ue923"));
//	faceTexts2.add(new FaceText("\\ue924"));
//	faceTexts2.add(new FaceText("\\ue925"));
//	faceTexts2.add(new FaceText("\\ue926"));
//	faceTexts2.add(new FaceText("\\ue927"));
//	faceTexts2.add(new FaceText("\\ue928"));
//	faceTexts2.add(new FaceText("\\ue929"));
//	faceTexts2.add(new FaceText("\\ue930"));
//	faceTexts2.add(new FaceText("\\ue931"));
//	faceTexts2.add(new FaceText("\\ue932"));
//	faceTexts2.add(new FaceText("\\ue933"));
//	faceTexts2.add(new FaceText("\\ue934"));
//	faceTexts2.add(new FaceText("\\ue935"));
//	faceTexts2.add(new FaceText("\\ue936"));
//	faceTexts2.add(new FaceText("\\ue937"));
//	faceTexts2.add(new FaceText("\\ue938"));
//	faceTexts2.add(new FaceText("\\ue939"));
//	faceTexts2.add(new FaceText("\\ue940"));
//	faceTexts2.add(new FaceText("\\ue941"));
//	faceTexts2.add(new FaceText("\\ue942"));
//	faceTexts2.add(new FaceText("\\ue943"));
//	faceTexts2.add(new FaceText("\\ue944"));
//	faceTexts2.add(new FaceText("\\ue945"));
//	faceTexts2.add(new FaceText("\\ue946"));
//	faceTexts2.add(new FaceText("\\ue947"));
//	faceTexts2.add(new FaceText("\\ue948"));
//	faceTexts2.add(new FaceText("\\ue949"));
//	faceTexts2.add(new FaceText("\\ue950"));
//	faceTexts2.add(new FaceText("\\ue951"));
//	faceTexts2.add(new FaceText("\\ue952"));
//	faceTexts2.add(new FaceText("\\ue953"));
//	faceTexts2.add(new FaceText("\\ue954"));
//	faceTexts2.add(new FaceText("\\ue955"));
//	faceTexts2.add(new FaceText("\\ue956"));
//	faceTexts2.add(new FaceText("\\ue957"));
//	faceTexts2.add(new FaceText("\\ue958"));
//	faceTexts2.add(new FaceText("\\ue959"));
//	faceTexts2.add(new FaceText("\\ue960"));
//	faceTexts2.add(new FaceText("\\ue961"));
//	faceTexts2.add(new FaceText("\\ue962"));
//	faceTexts2.add(new FaceText("\\ue963"));
//	faceTexts2.add(new FaceText("\\ue964"));
//	faceTexts2.add(new FaceText("\\ue965"));
//	faceTexts2.add(new FaceText("\\ue966"));
//	faceTexts2.add(new FaceText("\\ue967"));
//	faceTexts2.add(new FaceText("\\ue968"));
//	faceTexts2.add(new FaceText("\\ue969"));
//	faceTexts2.add(new FaceText("\\ue970"));
//	faceTexts2.add(new FaceText("\\ue971"));
//	faceTexts2.add(new FaceText("\\ue972"));
//	faceTexts2.add(new FaceText("\\ue973"));
//	faceTexts2.add(new FaceText("\\ue974"));
//	faceTexts2.add(new FaceText("\\ue975"));
//	faceTexts2.add(new FaceText("\\ue976"));
//	faceTexts2.add(new FaceText("\\ue977"));
//	faceTexts2.add(new FaceText("\\ue978"));
//	faceTexts2.add(new FaceText("\\ue979"));
//	faceTexts2.add(new FaceText("\\ue980"));
//	faceTexts2.add(new FaceText("\\ue981"));
//	faceTexts2.add(new FaceText("\\ue982"));
//	faceTexts2.add(new FaceText("\\ue983"));
//	faceTexts2.add(new FaceText("\\ue984"));
//	faceTexts2.add(new FaceText("\\ue985"));
//	faceTexts2.add(new FaceText("\\ue986"));
//	faceTexts2.add(new FaceText("\\ue987"));
//	faceTexts2.add(new FaceText("\\ue988"));
//	faceTexts2.add(new FaceText("\\ue989"));
//	faceTexts2.add(new FaceText("\\ue990"));
//	faceTexts2.add(new FaceText("\\ue991"));
//	faceTexts2.add(new FaceText("\\ue992"));
//	faceTexts2.add(new FaceText("\\ue993"));
//	faceTexts2.add(new FaceText("\\ue994"));
//	faceTexts2.add(new FaceText("\\ue995"));
//	faceTexts2.add(new FaceText("\\ue996"));
//	faceTexts2.add(new FaceText("\\ue997"));
//	faceTexts2.add(new FaceText("\\ue998"));
//	faceTexts2.add(new FaceText("\\ue999"));
//	faceTexts2.add(new FaceText("\\ue1000"));
//	faceTexts2.add(new FaceText("\\ue1001"));
//	faceTexts2.add(new FaceText("\\ue1002"));
//	faceTexts2.add(new FaceText("\\ue1003"));
//	faceTexts2.add(new FaceText("\\ue1004"));
//	faceTexts2.add(new FaceText("\\ue1005"));
//	faceTexts2.add(new FaceText("\\ue1006"));
//	faceTexts2.add(new FaceText("\\ue1007"));
//	faceTexts2.add(new FaceText("\\ue1008"));
//	faceTexts2.add(new FaceText("\\ue1009"));
//	faceTexts2.add(new FaceText("\\ue1010"));
//	faceTexts2.add(new FaceText("\\ue1011"));
//	faceTexts2.add(new FaceText("\\ue1012"));
//	faceTexts2.add(new FaceText("\\ue1013"));
//	faceTexts2.add(new FaceText("\\ue1014"));
//	faceTexts2.add(new FaceText("\\ue1015"));
//	faceTexts2.add(new FaceText("\\ue1016"));
//	faceTexts2.add(new FaceText("\\ue1017"));
//	faceTexts2.add(new FaceText("\\ue1018"));
//	faceTexts2.add(new FaceText("\\ue1019"));
//	faceTexts2.add(new FaceText("\\ue1020"));
//	faceTexts2.add(new FaceText("\\ue1021"));
//	faceTexts2.add(new FaceText("\\ue1022"));
//	faceTexts2.add(new FaceText("\\ue1023"));
//	faceTexts2.add(new FaceText("\\ue1024"));
//	faceTexts2.add(new FaceText("\\ue1025"));
//	faceTexts2.add(new FaceText("\\ue1026"));
//	faceTexts2.add(new FaceText("\\ue1027"));
//	faceTexts2.add(new FaceText("\\ue1028"));
//	faceTexts2.add(new FaceText("\\ue1029"));
//	faceTexts2.add(new FaceText("\\ue1030"));
//	faceTexts2.add(new FaceText("\\ue1031"));
//	faceTexts2.add(new FaceText("\\ue1032"));
//	faceTexts2.add(new FaceText("\\ue1033"));
//	faceTexts2.add(new FaceText("\\ue1034"));
//	faceTexts2.add(new FaceText("\\ue1035"));
//	faceTexts2.add(new FaceText("\\ue1036"));
//	faceTexts2.add(new FaceText("\\ue1037"));
//	faceTexts2.add(new FaceText("\\ue1038"));
//	faceTexts2.add(new FaceText("\\ue1039"));
//	faceTexts2.add(new FaceText("\\ue1040"));
//	faceTexts2.add(new FaceText("\\ue1041"));
//	faceTexts2.add(new FaceText("\\ue1042"));
//	faceTexts2.add(new FaceText("\\ue1043"));
//	faceTexts2.add(new FaceText("\\ue1044"));
//	faceTexts2.add(new FaceText("\\ue1045"));
//	faceTexts2.add(new FaceText("\\ue1046"));
//	faceTexts2.add(new FaceText("\\ue1047"));
//	faceTexts2.add(new FaceText("\\ue1048"));
//	faceTexts2.add(new FaceText("\\ue1049"));
//	faceTexts2.add(new FaceText("\\ue1050"));
//	faceTexts2.add(new FaceText("\\ue1051"));
//	faceTexts2.add(new FaceText("\\ue1052"));
//	faceTexts2.add(new FaceText("\\ue1053"));
//	faceTexts2.add(new FaceText("\\ue1054"));
//	faceTexts2.add(new FaceText("\\ue1055"));
//	faceTexts2.add(new FaceText("\\ue1056"));
//	faceTexts2.add(new FaceText("\\ue1057"));
//	faceTexts2.add(new FaceText("\\ue1058"));
//	faceTexts2.add(new FaceText("\\ue1059"));
//	faceTexts2.add(new FaceText("\\ue1060"));
//	faceTexts2.add(new FaceText("\\ue1061"));
//	faceTexts2.add(new FaceText("\\ue1062"));
//	faceTexts2.add(new FaceText("\\ue1063"));
//	faceTexts2.add(new FaceText("\\ue1064"));
//	faceTexts2.add(new FaceText("\\ue1065"));
//	faceTexts2.add(new FaceText("\\ue1066"));
//	faceTexts2.add(new FaceText("\\ue1067"));
//	faceTexts2.add(new FaceText("\\ue1068"));
//	faceTexts2.add(new FaceText("\\ue1069"));
//	faceTexts2.add(new FaceText("\\ue1070"));
//	faceTexts2.add(new FaceText("\\ue1071"));
//	faceTexts2.add(new FaceText("\\ue1072"));
//	faceTexts2.add(new FaceText("\\ue1073"));
//	faceTexts2.add(new FaceText("\\ue1074"));
//	faceTexts2.add(new FaceText("\\ue1075"));
//	faceTexts2.add(new FaceText("\\ue1076"));
//	faceTexts2.add(new FaceText("\\ue1077"));
//	faceTexts2.add(new FaceText("\\ue1078"));
//	faceTexts2.add(new FaceText("\\ue1079"));
//	faceTexts2.add(new FaceText("\\ue1080"));
//	faceTexts2.add(new FaceText("\\ue1081"));
//	faceTexts2.add(new FaceText("\\ue1082"));
//	faceTexts2.add(new FaceText("\\ue1083"));
//	faceTexts2.add(new FaceText("\\ue1084"));
//	faceTexts2.add(new FaceText("\\ue1085"));
//	faceTexts2.add(new FaceText("\\ue1086"));
//	faceTexts2.add(new FaceText("\\ue1087"));
//	faceTexts2.add(new FaceText("\\ue1088"));
//	faceTexts2.add(new FaceText("\\ue1089"));
//	faceTexts2.add(new FaceText("\\ue1090"));
//	faceTexts2.add(new FaceText("\\ue1091"));
//	faceTexts2.add(new FaceText("\\ue1092"));
//	faceTexts2.add(new FaceText("\\ue1093"));
//	faceTexts2.add(new FaceText("\\ue1094"));
//	faceTexts2.add(new FaceText("\\ue1095"));
//	faceTexts2.add(new FaceText("\\ue1096"));
//	faceTexts2.add(new FaceText("\\ue1097"));
//	faceTexts2.add(new FaceText("\\ue1098"));
//	faceTexts2.add(new FaceText("\\ue1099"));
//	faceTexts2.add(new FaceText("\\ue1100"));
//	faceTexts2.add(new FaceText("\\ue1101"));
//	faceTexts2.add(new FaceText("\\ue1102"));
//	faceTexts2.add(new FaceText("\\ue1103"));
//	faceTexts2.add(new FaceText("\\ue1104"));
//	faceTexts2.add(new FaceText("\\ue1105"));
//	faceTexts2.add(new FaceText("\\ue1106"));
//	faceTexts2.add(new FaceText("\\ue1107"));
//	faceTexts2.add(new FaceText("\\ue1108"));
//	faceTexts2.add(new FaceText("\\ue1109"));
//	faceTexts2.add(new FaceText("\\ue1110"));
//	faceTexts2.add(new FaceText("\\ue1111"));
//	faceTexts2.add(new FaceText("\\ue1112"));
//	faceTexts2.add(new FaceText("\\ue1113"));
//	faceTexts2.add(new FaceText("\\ue1114"));
//	faceTexts2.add(new FaceText("\\ue1115"));
//	faceTexts2.add(new FaceText("\\ue1116"));
//	faceTexts2.add(new FaceText("\\ue1117"));
//	faceTexts2.add(new FaceText("\\ue1118"));
//	faceTexts2.add(new FaceText("\\ue1119"));
//	faceTexts2.add(new FaceText("\\ue1120"));
//	faceTexts2.add(new FaceText("\\ue1121"));
//	faceTexts2.add(new FaceText("\\ue1122"));
//	faceTexts2.add(new FaceText("\\ue1123"));
//	faceTexts2.add(new FaceText("\\ue1124"));
//	faceTexts2.add(new FaceText("\\ue1125"));
//	faceTexts2.add(new FaceText("\\ue1126"));
//	faceTexts2.add(new FaceText("\\ue1127"));
//	faceTexts2.add(new FaceText("\\ue1128"));
//	faceTexts2.add(new FaceText("\\ue1129"));
//	faceTexts2.add(new FaceText("\\ue1130"));
//	faceTexts2.add(new FaceText("\\ue1131"));
//	faceTexts2.add(new FaceText("\\ue1132"));
//	faceTexts2.add(new FaceText("\\ue1133"));
//	faceTexts2.add(new FaceText("\\ue1134"));
//	faceTexts2.add(new FaceText("\\ue1135"));
//	faceTexts2.add(new FaceText("\\ue1136"));
//	faceTexts2.add(new FaceText("\\ue1137"));
//	faceTexts2.add(new FaceText("\\ue1138"));
//	faceTexts2.add(new FaceText("\\ue1139"));
//	faceTexts2.add(new FaceText("\\ue1140"));
//	faceTexts2.add(new FaceText("\\ue1141"));
//	faceTexts2.add(new FaceText("\\ue1142"));
//	faceTexts2.add(new FaceText("\\ue1143"));
//	faceTexts2.add(new FaceText("\\ue1144"));
//	faceTexts2.add(new FaceText("\\ue1145"));
//	faceTexts2.add(new FaceText("\\ue1146"));
//	faceTexts2.add(new FaceText("\\ue1147"));
//	faceTexts2.add(new FaceText("\\ue1148"));
//	faceTexts2.add(new FaceText("\\ue1149"));
//	faceTexts2.add(new FaceText("\\ue1150"));
//	faceTexts2.add(new FaceText("\\ue1151"));
//	faceTexts2.add(new FaceText("\\ue1152"));
//	faceTexts2.add(new FaceText("\\ue1153"));
//	faceTexts2.add(new FaceText("\\ue1154"));
//	faceTexts2.add(new FaceText("\\ue1155"));
//	faceTexts2.add(new FaceText("\\ue1156"));
//	faceTexts2.add(new FaceText("\\ue1157"));
//	faceTexts2.add(new FaceText("\\ue1158"));
//	faceTexts2.add(new FaceText("\\ue1159"));
//	faceTexts2.add(new FaceText("\\ue1160"));
//	faceTexts2.add(new FaceText("\\ue1161"));
//	faceTexts2.add(new FaceText("\\ue1162"));
//	faceTexts2.add(new FaceText("\\ue1163"));
//	faceTexts2.add(new FaceText("\\ue1164"));
//	faceTexts2.add(new FaceText("\\ue1165"));
//	faceTexts2.add(new FaceText("\\ue1166"));
//	faceTexts2.add(new FaceText("\\ue1167"));
//	faceTexts2.add(new FaceText("\\ue1168"));
//	faceTexts2.add(new FaceText("\\ue1169"));
//	faceTexts2.add(new FaceText("\\ue1170"));
//	faceTexts2.add(new FaceText("\\ue1171"));
//	faceTexts2.add(new FaceText("\\ue1172"));
//	faceTexts2.add(new FaceText("\\ue1173"));
//	faceTexts2.add(new FaceText("\\ue1174"));
//	faceTexts2.add(new FaceText("\\ue1175"));
//	faceTexts2.add(new FaceText("\\ue1176"));
//	faceTexts2.add(new FaceText("\\ue1177"));
//	faceTexts2.add(new FaceText("\\ue1178"));
//	faceTexts2.add(new FaceText("\\ue1179"));
//	faceTexts2.add(new FaceText("\\ue1180"));
//	faceTexts2.add(new FaceText("\\ue1181"));
//	faceTexts2.add(new FaceText("\\ue1182"));
//	faceTexts2.add(new FaceText("\\ue1183"));
//	faceTexts2.add(new FaceText("\\ue1184"));
//	faceTexts2.add(new FaceText("\\ue1185"));
//	faceTexts2.add(new FaceText("\\ue1186"));
//	faceTexts2.add(new FaceText("\\ue1187"));
//	faceTexts2.add(new FaceText("\\ue1188"));
//	faceTexts2.add(new FaceText("\\ue1189"));
//	faceTexts2.add(new FaceText("\\ue1190"));
//	faceTexts2.add(new FaceText("\\ue1191"));
//	faceTexts2.add(new FaceText("\\ue1192"));
//	faceTexts2.add(new FaceText("\\ue1193"));
//	faceTexts2.add(new FaceText("\\ue1194"));
//	faceTexts2.add(new FaceText("\\ue1195"));
//	faceTexts2.add(new FaceText("\\ue1196"));
//	faceTexts2.add(new FaceText("\\ue1197"));
//	faceTexts2.add(new FaceText("\\ue1198"));
//	faceTexts2.add(new FaceText("\\ue1199"));
//	faceTexts2.add(new FaceText("\\ue1200"));
//	faceTexts2.add(new FaceText("\\ue1201"));
//	faceTexts2.add(new FaceText("\\ue1202"));
//	faceTexts2.add(new FaceText("\\ue1203"));
//	faceTexts2.add(new FaceText("\\ue1204"));
//	faceTexts2.add(new FaceText("\\ue1205"));
//	faceTexts2.add(new FaceText("\\ue1206"));
//	faceTexts2.add(new FaceText("\\ue1207"));
//	faceTexts2.add(new FaceText("\\ue1208"));
//	faceTexts2.add(new FaceText("\\ue1209"));
//	faceTexts2.add(new FaceText("\\ue1210"));
//	faceTexts2.add(new FaceText("\\ue1211"));
//	faceTexts2.add(new FaceText("\\ue1212"));
//	faceTexts2.add(new FaceText("\\ue1213"));
//	faceTexts2.add(new FaceText("\\ue1214"));
//	faceTexts2.add(new FaceText("\\ue1215"));
//	faceTexts2.add(new FaceText("\\ue1216"));
//	faceTexts2.add(new FaceText("\\ue1217"));
//	faceTexts2.add(new FaceText("\\ue1218"));
//	faceTexts2.add(new FaceText("\\ue1219"));
//	faceTexts2.add(new FaceText("\\ue1220"));
//	faceTexts2.add(new FaceText("\\ue1221"));
//	faceTexts2.add(new FaceText("\\ue1222"));
//	faceTexts2.add(new FaceText("\\ue1223"));
//	faceTexts2.add(new FaceText("\\ue1224"));
//	faceTexts2.add(new FaceText("\\ue1225"));
//	faceTexts2.add(new FaceText("\\ue1226"));
//	faceTexts2.add(new FaceText("\\ue1227"));
//	faceTexts2.add(new FaceText("\\ue1228"));
//	faceTexts2.add(new FaceText("\\ue1229"));
//	faceTexts2.add(new FaceText("\\ue1230"));
//	faceTexts2.add(new FaceText("\\ue1231"));
//	faceTexts2.add(new FaceText("\\ue1232"));
//	faceTexts2.add(new FaceText("\\ue1233"));
//	faceTexts2.add(new FaceText("\\ue1234"));
//	faceTexts2.add(new FaceText("\\ue1235"));
//	faceTexts2.add(new FaceText("\\ue1236"));
//	faceTexts2.add(new FaceText("\\ue1237"));
//	faceTexts2.add(new FaceText("\\ue1238"));
//	faceTexts2.add(new FaceText("\\ue1239"));
//	faceTexts2.add(new FaceText("\\ue1240"));
//	faceTexts2.add(new FaceText("\\ue1241"));
//	faceTexts2.add(new FaceText("\\ue1242"));
//	faceTexts2.add(new FaceText("\\ue1243"));
//	faceTexts2.add(new FaceText("\\ue1244"));
//	faceTexts2.add(new FaceText("\\ue1245"));
//	faceTexts2.add(new FaceText("\\ue1246"));
//	faceTexts2.add(new FaceText("\\ue1247"));
//	faceTexts2.add(new FaceText("\\ue1248"));
//	faceTexts2.add(new FaceText("\\ue1249"));
//	faceTexts2.add(new FaceText("\\ue1250"));
//	faceTexts2.add(new FaceText("\\ue1251"));
//	faceTexts2.add(new FaceText("\\ue1252"));
//	faceTexts2.add(new FaceText("\\ue1253"));
//	faceTexts2.add(new FaceText("\\ue1254"));
//	faceTexts2.add(new FaceText("\\ue1255"));
//	faceTexts2.add(new FaceText("\\ue1256"));
//	faceTexts2.add(new FaceText("\\ue1257"));
//	faceTexts2.add(new FaceText("\\ue1258"));
//	faceTexts2.add(new FaceText("\\ue1259"));
//	faceTexts2.add(new FaceText("\\ue1260"));
//	faceTexts2.add(new FaceText("\\ue1261"));
//	faceTexts2.add(new FaceText("\\ue1262"));
//	faceTexts2.add(new FaceText("\\ue1263"));
//	faceTexts2.add(new FaceText("\\ue1264"));
//	faceTexts2.add(new FaceText("\\ue1265"));
//	faceTexts2.add(new FaceText("\\ue1266"));
//	faceTexts2.add(new FaceText("\\ue1267"));
//	faceTexts2.add(new FaceText("\\ue1268"));
//	faceTexts2.add(new FaceText("\\ue1269"));
//	faceTexts2.add(new FaceText("\\ue1270"));
//	faceTexts2.add(new FaceText("\\ue1271"));
//	faceTexts2.add(new FaceText("\\ue1272"));
//	faceTexts2.add(new FaceText("\\ue1273"));
//	faceTexts2.add(new FaceText("\\ue1274"));
//	faceTexts2.add(new FaceText("\\ue1275"));
//	faceTexts2.add(new FaceText("\\ue1276"));
//	faceTexts2.add(new FaceText("\\ue1277"));
//	faceTexts2.add(new FaceText("\\ue1278"));
//	faceTexts2.add(new FaceText("\\ue1279"));
//	faceTexts2.add(new FaceText("\\ue1280"));
//	faceTexts2.add(new FaceText("\\ue1281"));
//	faceTexts2.add(new FaceText("\\ue1282"));
//	faceTexts2.add(new FaceText("\\ue1283"));
//	faceTexts2.add(new FaceText("\\ue1284"));
//	faceTexts2.add(new FaceText("\\ue1285"));
//	faceTexts2.add(new FaceText("\\ue1286"));
//	faceTexts2.add(new FaceText("\\ue1287"));
//	faceTexts2.add(new FaceText("\\ue1288"));
//	faceTexts2.add(new FaceText("\\ue1289"));
//	faceTexts2.add(new FaceText("\\ue1290"));
//	faceTexts2.add(new FaceText("\\ue1291"));
//	faceTexts2.add(new FaceText("\\ue1292"));
//	faceTexts2.add(new FaceText("\\ue1293"));
//	faceTexts2.add(new FaceText("\\ue1294"));
//	faceTexts2.add(new FaceText("\\ue1295"));
//	faceTexts2.add(new FaceText("\\ue1296"));
//	faceTexts2.add(new FaceText("\\ue1297"));
//	faceTexts2.add(new FaceText("\\ue1298"));
//	faceTexts2.add(new FaceText("\\ue1299"));
//	faceTexts2.add(new FaceText("\\ue1300"));
//	faceTexts2.add(new FaceText("\\ue1301"));
//	faceTexts2.add(new FaceText("\\ue1302"));
//	faceTexts2.add(new FaceText("\\ue1303"));
//	faceTexts2.add(new FaceText("\\ue1304"));
//	faceTexts2.add(new FaceText("\\ue1305"));
//	faceTexts2.add(new FaceText("\\ue1306"));
//	faceTexts2.add(new FaceText("\\ue1307"));
//	faceTexts2.add(new FaceText("\\ue1308"));
//	faceTexts2.add(new FaceText("\\ue1309"));
//	faceTexts2.add(new FaceText("\\ue1310"));
//	faceTexts2.add(new FaceText("\\ue1311"));
//	faceTexts2.add(new FaceText("\\ue1312"));
//	faceTexts2.add(new FaceText("\\ue1313"));
//	faceTexts2.add(new FaceText("\\ue1314"));
//	faceTexts2.add(new FaceText("\\ue1315"));
//	faceTexts2.add(new FaceText("\\ue1316"));
//	faceTexts2.add(new FaceText("\\ue1317"));
//	faceTexts2.add(new FaceText("\\ue1318"));
//	faceTexts2.add(new FaceText("\\ue1319"));
//	faceTexts2.add(new FaceText("\\ue1320"));
//	faceTexts2.add(new FaceText("\\ue1321"));
//	faceTexts2.add(new FaceText("\\ue1322"));
//	faceTexts2.add(new FaceText("\\ue1323"));
//	faceTexts2.add(new FaceText("\\ue1324"));
//	faceTexts2.add(new FaceText("\\ue1325"));
//	faceTexts2.add(new FaceText("\\ue1326"));
//	faceTexts2.add(new FaceText("\\ue1327"));
//	faceTexts2.add(new FaceText("\\ue1328"));
//	faceTexts2.add(new FaceText("\\ue1329"));
//	faceTexts2.add(new FaceText("\\ue1330"));
//	faceTexts2.add(new FaceText("\\ue1331"));
//	faceTexts2.add(new FaceText("\\ue1332"));
//	faceTexts2.add(new FaceText("\\ue1333"));
//	faceTexts2.add(new FaceText("\\ue1334"));
//	faceTexts2.add(new FaceText("\\ue1335"));
//	faceTexts2.add(new FaceText("\\ue1336"));
//	faceTexts2.add(new FaceText("\\ue1337"));
//	faceTexts2.add(new FaceText("\\ue1338"));
//	faceTexts2.add(new FaceText("\\ue1339"));
//	faceTexts2.add(new FaceText("\\ue1340"));
//	faceTexts2.add(new FaceText("\\ue1341"));
//	faceTexts2.add(new FaceText("\\ue1342"));
//	faceTexts2.add(new FaceText("\\ue1343"));
//	faceTexts2.add(new FaceText("\\ue1344"));
//	faceTexts2.add(new FaceText("\\ue1345"));
//	faceTexts2.add(new FaceText("\\ue1346"));
//	faceTexts2.add(new FaceText("\\ue1347"));
//	faceTexts2.add(new FaceText("\\ue1348"));
//	faceTexts2.add(new FaceText("\\ue1349"));
//	faceTexts2.add(new FaceText("\\ue1350"));
//
//    }

    public static String parse(String s) {
	for (FaceText faceText : faceTexts) {
	    s = s.replace("\\" + faceText.text, faceText.text);
	    s = s.replace(faceText.text, "\\" + faceText.text);
	}
	return s;
    }

    /** 
      * toSpannableString
      * @return SpannableString
      * @throws
      */
    public static SpannableString toSpannableString(Context context, String text) {
	if (!TextUtils.isEmpty(text)) {
	    SpannableString spannableString = new SpannableString(text);
	    int start = 0;
	    Pattern pattern = Pattern.compile("\\\\ue[a-z0-9]{3,4}", Pattern.CASE_INSENSITIVE);
	    Matcher matcher = pattern.matcher(text);
	    while (matcher.find()) {
		String faceText = matcher.group();
		String key = faceText.substring(1);
		BitmapFactory.Options options = new BitmapFactory.Options();
		Bitmap bitmap = BitmapFactory.decodeResource(context.getResources(), context.getResources().getIdentifier(key, "drawable", context.getPackageName()), options);
		ImageSpan imageSpan = new ImageSpan(context, bitmap);
		int startIndex = text.indexOf(faceText, start);
		int endIndex = startIndex + faceText.length();
		if (startIndex >= 0)
		    spannableString.setSpan(imageSpan, startIndex, endIndex, Spannable.SPAN_EXCLUSIVE_EXCLUSIVE);
		start = (endIndex - 1);
	    }

	    return spannableString;
	} else {
	    return new SpannableString("");
	}
    }

    public static SpannableString toSpannableString(Context context, String text, SpannableString spannableString) {

	int start = 0;
	Pattern pattern = Pattern.compile("\\\\ue[a-z0-9]{3,4}", Pattern.CASE_INSENSITIVE);
	Matcher matcher = pattern.matcher(text);
	while (matcher.find()) {
	    String faceText = matcher.group();
	    String key = faceText.substring(1);
	    BitmapFactory.Options options = new BitmapFactory.Options();
	    //			options.inSampleSize = 2;
	    Bitmap bitmap = BitmapFactory.decodeResource(context.getResources(), context.getResources().getIdentifier(key, "drawable", context.getPackageName()), options);
	    ImageSpan imageSpan = new ImageSpan(context, bitmap);
	    int startIndex = text.indexOf(faceText, start);
	    int endIndex = startIndex + faceText.length();
	    if (startIndex >= 0)
		spannableString.setSpan(imageSpan, startIndex, endIndex, Spannable.SPAN_EXCLUSIVE_EXCLUSIVE);
	    start = (endIndex - 1);
	}

	return spannableString;
    }

    /**
     * 去掉所有表情内容
     * @param text
     * @return
     */
    public static String trimAllFace(String text) {
	return text.replaceAll("\\\\ue[a-z0-9]{3,4}", "");
    }

}
